#!/bin/bash

# 
xrandr --pdi 120

# Establece el fondo de pantalla
 exec ~/.fehbg &

# Inicia un terminal Xfce
xfce4-terminal &

# ## xfce4-settings daemon
xfsettingsd &
#
# ## Start Compositing Manager
# ob-compositor --start &
sleep 2

# Lanzar Polybar
sh ~/.config/polybar/launch.sh &

# Thunar Daemon
thunar --daemon &

